In [1]:
import numpy as np
#시작할 때 불러와줘야 함,아나콘다 안에 있음

In [2]:
#1차원 배열 만들기
#ndarray 클래스 객체

In [3]:
ar = np.array([ _ for _ in range(10)]) 
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
ar.shape
(10,)
#1차원의 10칸 갖는 ndarray

(10,)

In [5]:
#np.array()로 생성한 객체는 -> numpy.ndarray타입을 가짐

In [6]:
type(ar)

numpy.ndarray

In [7]:
#리스트 자료형은는 요소의 종류에 관계없이, 또 개수에 제한없이 삽입, 삭제, 수정 가능
#넘파이 배열 객체는 C언어의 배열처럼 메모리에서 연속적인 배치를 이룸
#즉, 모든 요소가 같은 자료형이어야 하고 개수가 명확해야 함

In [8]:
#int
#32bit 컴퓨터 기준으로 정수가 32bit (4byte) 크기라고 가정한다면 int 자료형은 2의 32제곱의 값(4,294,967,296)을 표현할 수 있다.
#음수, 0, 양수를 포함하여 최소 -2,147,483,648에서 최대 2,147,483,647까지 표현하는 것이다.
#ex. 쥬니어네이버 동물농장 포인트는 21억이 최대였다.
#ex. 마인크래프트 레벨은 21억이 최대다.

#unsigned int
#unsigned int 자료형은 int의 범위를 양의 정수 범위로만 사용한 자료형이다.
#따라서 양의 표현이 2배 늘어난다. 최소 0부터 최대 4,294,967,295까지 표현한다.
#ex. 바람의 나라 최대 경험치는 42.9억이다.

In [9]:
#같은 타입인 정수를 요소로 갖는 리스트를 활용
ar = np.array([ _ for _ in range(10)]) 
ar
#ar2의 경우를 살펴보면 정수와 실수가 혼합된 리스트를 활용하여 ndarray 객체를 생성하고 있습니다. 
#앞서 정수와 실수의 연산과 같은 맥락으로 실수 타입으로 모두 선언된 것을 확인할 수 있습니다.
#표현 범위가 더 큰 자료형으로 변환
ar2 = np.array([0.1,5,4,12 ,0.5])
ar2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [10]:
#넘파이의 배열인 ndarray클래스는 요소가 모두 같은 자료형을 갖는다고 했습니다. 
#np.array() 함수로 넘파이 배열을 만들 때 자료형을 명시적으로 작성하려면 키워드인자로 dtype을 사용합니다. 
#반대로 dtype 키워드 인수가 없으면 해당 데이터 자료형을 동적 타이핑합니다. 
#그리고 만들어진 넘파이 배열의 자료형을 확인하려면 dtype 속성을 활용하면 됩니다
import numpy as np
x = np.array([1,2,3])
x.dtype

dtype('int32')

In [11]:
x = np.array([1.0,2.0,3.0])
x.dtype

dtype('float64')

In [12]:
x = np.array([1,2,3.0])
x.dtype

dtype('float64')

In [13]:
#넘파이의 자료형
#dtype지정 가능
import numpy as np
x = np.array([1,2,3],dtype = 'f')
x.dtype

dtype('float32')

In [14]:
x[0]+x[1]
type(x[0]+x[1])

numpy.float32

In [15]:
x = np.array([1,2,3],dtype = 'U')
x.dtype
#최대 1칸짜리만 만들 수 있음

dtype('<U1')

In [16]:
x[0]+x[1] #str

'12'

In [17]:
#무한대를 표현하기 위한 np.inf(infinity)와 
#정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용
np.array([0,1,-1,0])/np.array([1,0,0,0])
#다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 
#무한대인 np.inf이 나옵니다. 
#0을 0으로 나누려고 시도하면 np.nan이 나옵니다
#각 값이 순서에 따라 매칭되어 차례로 나뉨 ->0/1,1/0,-1/0,0/0

C:\Users\Playdata\AppData\Local\Temp\ipykernel_14672\2482597711.py:3: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])
C:\Users\Playdata\AppData\Local\Temp\ipykernel_14672\2482597711.py:3: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0])/np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [18]:
np.log(0)

C:\Users\Playdata\AppData\Local\Temp\ipykernel_14672\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [19]:
np.exp(-np.inf)

0.0

In [20]:
#벡터화 연산(Vectorized Operation)
#배열의 각 요소에 대한 반복 연산을 하나의 명령어로 처리
#리스트 내 모든 요소 데이터를 모두 2배 해야 하는 경우

In [21]:
data = [0,1,2,3,4,5,6,7,8,9]
answer = [2 * d for d in data]
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [22]:
#넘파이 배열 객체의 벡터화 연산을 사용하면 다음과 같이 for 반복문이 없이 간단하게 단 한번의 연산식으로 표현
x = np.array(data)
x
#처리 속도도 더 빠름

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
#파이썬 리스트 객체에 정수를 곱하면(*) 객체의 크기가 곱한 숫자만큼 반복 증가합니다. 
#넘파이 배열 객체는 벡터화 연산이 이뤄진다
list_samp =[ _ for _ in range(3)]
print(list_samp*3)

[0, 1, 2, 0, 1, 2, 0, 1, 2]


In [25]:
a = np.array([1,2,3])
b = np.array([10,20,30])
2 * a + b

array([12, 24, 36])

In [26]:
a == 2

array([False,  True, False])

In [27]:
b>10

array([False,  True,  True])

In [28]:
(a == 2) & (b > 10)
#and는 쓸 수 없음
#소괄호 꼭 써주어야 함 - 우선순위 때문에
#벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용

array([False,  True, False])

In [29]:
#2차원 배열 만들기

In [30]:
#행렬(matrix)
#가로줄 -> 행(row)
#세로줄 ->열(column)

In [31]:
#리스트를 중첩하여 리스트의 리스트(list of list)를 이용해서 2차원 배열처럼 생성
#안쪽 리스트의 길이는 행렬의 열의 수 즉 가로 크기
#바깥쪽 리스트의 길이는 행렬의 행의 수, 즉 세로 크기
c = np.array([[0,1,2],[3,4,5]]) #2행 *3열 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [32]:
#행의 갯수
len(c)

2

In [33]:
#열의 개수
len(c[0])

3

In [34]:
#2차원 배열의 행과 열의 개수는 앞서 다뤘던 넘파이 배열 객체의 속성 shape를 활용하여 구할 수
c.shape

(2, 3)

In [35]:
d = np.array([[10,20,30,40],
              [50,60,70,80]])
d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [36]:
d = np.array([[10,20,30,40],[50,60,70,80]])
d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [37]:
#3차원 배열 만들기
#깊이 x 행 x 열
#리스트의 리스트의 리스트를 이용
#크기를 나타낼 때는 가장 바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이의 순서로 표시 
#2 x 3 x 4 배열은 다음과 같이 만듭니다
e = np.array([[[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]],
             [[1,12,13,14],
              [15,16,17,18],
              [19,20,21,22]]])
e

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [38]:
e.dtype

dtype('int32')

In [39]:
e.shape

(2, 3, 4)

In [40]:
#3차원 배열의 깊이, 행, 열은 다음과 같이 구할 수 있습니다
len(e),len(e[0]),len(e[0][0])

(2, 3, 4)

In [41]:
#배열의 차원과 크기 알아내기
#배열의 ndim 속성과 shape 속성을 이용
#ndim 속성은 배열의 차원 shape 속성은 배열의 크기를 반환
#a = np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [42]:
#c = np.array([[0,1,2],[3,4,5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [43]:
print(e.ndim)
print(e.shape)

3
(2, 3, 4)


In [44]:
#배열의 인덱싱

In [45]:
#일차원 배열의 인덱싱은 리스트의 인덱싱과 같음
a = np.array([0,1,2,3,4])
a[2]

2

In [46]:
a[-1]

4

In [47]:
#다차원 배열일 때는 다음과 같이 콤마(comma ,)를 사용하여 접근
#콤마로 구분된 차원을 축(axis)
#그래프의 x축과 y축
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
a[0,0] #첫번째 행의 첫번재 열

0

In [49]:
a[0,1] #첫번째 행의 두번째 열

1

In [50]:
a[-1,-1] #마지막 행의 마지막 열

5

In [51]:
#리스트 슬라이싱
a = [[0,1,2,3],[4,5,6,7]] #a에서 1,2,3의 값을 가져오기
a[0][0:3:1]

[0, 1, 2]

In [52]:
#배열의 슬라이싱
#배열 객체로 구현한 다차원 배열의 원소 중 복수 개를 접근하려면 일반적인 파이썬 
#슬라이싱(slicing)과 comma(,)를 함께 사용
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [53]:
a[0, :] #첫번째 행 전체 #:뒤는 전체라는 뜻

array([0, 1, 2, 3])

In [54]:
a[:,1] #두번째 열 전체

array([1, 5])

In [55]:
a[1,1:] #두번째 행의 두번째 열부터 끝열까지

array([5, 6, 7])

In [56]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

In [57]:
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])
#7인덱싱
#14인덱싱
#[6,7]슬라이싱
#[7,12]슬라이싱
#[[3,4],[8,9]]슬라이싱
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
m[1,2]

7

In [59]:
m[2,-1]
#index 2 is out of bounds for axis 0 with size 2

14

In [60]:
m[1,1:3:1]

array([6, 7])

In [61]:
m[1:,2:3]

array([[ 7],
       [12]])

In [62]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

In [63]:
#배열 생성

In [64]:
#NumPy는 몇가지 단순한 배열을 생성하는 명령을 제공
#zeros, ones
#zeros_like, ones_like
#empty
#arange
#linspace, logspace #간격동일, 로그 간격
#크기가 정해져 있고 모든 값이 0인 배열을 생성하려면 zeros 메서드를 사용
#첫번째 인수로는 shape 혹은 1차원 배열을 크기를 뜻하는 정수를 넣습니다

In [65]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [66]:
zeros.dtype

dtype('float64')

In [67]:
#shape를 의미하는 튜플 값을 첫 번째 인수로 입력하면 다차원 배열도 쉽게 만듦
#array 명령과 마찬가지로 dtype 인수를 명시하면 해당 자료형 요소소를 가진 배열을 만듭니다
c = np.zeros((5,2),dtype = "i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [68]:
#zeros 메서드로 문자열 배열도 생성 가능하지만 
#모든 요소의 문자열 크기가 같아야 합니다. 
#만약 더 큰 크기의 문자열을 할당하면 잘릴 수 있습니다.
d = np.zeros(5,dtype = "U4") #unicode
#U뒤의 글자가 4이기 때문에 네글자밖에 안들어감
d

array(['', '', '', '', ''], dtype='<U4')

In [69]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "abcde" #위의 이유로 e가 잘림
d

array(['abc', 'abcd', 'abcd', '', ''], dtype='<U4')

In [70]:
#0이 아닌 1로 초기화된 배열을 생성하려면 ones 명령을 사용합니다
e = np.ones((2,3,4),dtype = "i8") #int
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [71]:
#shape를 튜플 값으로 명시하지 않고 다른 배열과 같은 shape의 배열을 생성하고 싶다면 
#ones_like, zeros_like 명령을 사용합니다.
#첫 번째 인수로는 shape을 복사하고 싶은 ndarray 객체를 작성합니다
f = np.ones_like(b,dtype="f")
f

array([1., 1., 1.], dtype=float32)

In [72]:
f = np.zeros_like(b,dtype="U10")
f

array(['', '', ''], dtype='<U10')

In [73]:
#배열의 크기가 커지면 배열을 초기화하는데도 시간이 걸립니다. 
#이 시간을 단축하려면 배열을 생성만 하고 특정한 값으로 초기화를 하지 않는 
#empty 명령을 사용할 수 있습니다
#empty 명령으로 생성된 배열에는 기존에 메모리에 저장되어 있던 값이 있으므로 
#배열의 요소의 값을 미리 알 수 없습니다
g = np.empty((4,3)) #모양만 잡는 쓰레기 값 #랜덤한 값
g

array([[1.18750201e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.06099790e-312, 1.55974036e+161],
       [4.74624283e-037, 6.15418096e+170, 9.32667200e+164],
       [3.40713395e+175, 3.27802162e+179, 9.76694654e+165]])

In [74]:
#arange 명령은 NumPy 버전의 range 명령이라고 볼 수 있습니다. 
#특정한 규칙에 따라 증가하는 수열을 만듭니다.

np.arange(10) #0...n+1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
np.arange(3,21,2) #시작, 끝(포함하지 않음),단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [76]:
#linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할합니다
ex = np.linspace(0,100,5) #범위만큼 간격을 두고 숫자를 만들어준다
ex #끝 범위 포함

array([  0.,  25.,  50.,  75., 100.])

In [77]:
ex1 = np.linspace(0,100,10) #범위만큼 간격을 두고 숫자를 만들어준다
ex1

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [78]:
ex2 = np.logspace(0,100,5) #log범위만큼 간격을 두고 숫자를 만들어준다
ex2

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

In [79]:
#전치 연산
#행과 열을 바꾸는 작업입니다. 
#이는 배열의 T 속성으로 구할 수 있습니다. 메서드가 아닌 속성이라는 점에 유의합니다
A = np.array([[1,2,3],[4,5,6]]) #2*3
A

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
A.T #3*2

array([[1, 4],
       [2, 5],
       [3, 6]])

In [81]:
#배열의 크기 변형
#만들어진 배열의 내부 데이터는 보존한 채로 형태만 바꾸려면 reshape 명령이나 메서드를 사용합니다.
#예를 들어 12개의 원소를 가진 1차원 행렬은 3x4 형태의 2차원 행렬로 만들 수 있습니다
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [82]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
#배열의 크기 변형
#사용하는 원소의 개수가 정해져 있기 때문에 
#reshape 명령의 형태 튜플의 원소 중 하나는 -1이라는 숫자로 대체할 수 있습니다. 
#-1을 넣으면 해당 숫자는 다를 값에서 계산되어 사용됩니다
a.reshape(3,-1) #행 3개를 만들고 열은 알아서 계산하라

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [85]:
a.reshape(2,2,-1).shape

(2, 2, 3)

In [86]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [87]:
a.reshape(2,-1,2).shape

(2, 3, 2)

In [88]:
#배열의 크기 변형
#다차원 배열을 1차원으로 만들기 위해서는 flatten 혹은 ravel 메서드를 사용
a.flatten

<function ndarray.flatten>

In [89]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [90]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [91]:
#배열 사용에서 주의할 점은 
#길이가 5인 1차원 배열과 행, 
#열의 개수가 (5, 1)인 2차원 배열 또는
#행, 열의 개수가 (1, 5)인 2차원 배열은 
#데이터가 같아도 엄연히 다른 객체라는 점입니다

In [92]:
x = np.arange(5)
x
id(x)

2403567776464

In [93]:
x.reshape(1,5)
id(x)

2403567776464

In [94]:
x.reshape(5,1)
id(x)

2403567776464

In [95]:
#같은 배열에 대해 차원만 1차원 증가시키는 경우에는 newaxis 명령을 사용하기도 합니다
x[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [96]:
#배열 연결

In [97]:
#행의 수나 열의 수가 같은 두 개 이상의 배열을 연결하여(concatenate) 더 큰 배열을 만들 때
# hstack
# vstack
# dstack
# stack
# r_
# c_
# tile

In [98]:
#hstock
#hstack 명령은 행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더 많은 배열을 만듭니다. 
#연결할 배열은 하나의 리스트에 담아야 합니다
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [99]:
a2 = np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [100]:
np.hstack([a1,a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [101]:
#vstack 명령은 열의 수가 같은 두 개 이상의 배열을 위아래로 연결하여 행의 수가 더 많은 배열을 만듭니다. 
#연결할 배열은 마찬가지로 하나의 리스트에 담아야 합니다
b1 = np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [102]:
b2 = np.zeros((3,3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [103]:
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [104]:
#dstack 명령은 제3의 축 즉, 행이나 열이 아닌 깊이(depth) 방향으로 배열을 합칩니다. 
#가장 안쪽의 원소의 차원이 증가합니다. 
#즉 가장 내부의 숫자 원소가 배열이 됩니다. 
#shape 정보로 보자면 가장 끝에 값이 2인 차원이 추가되는 것입니다.
#이 예제의 경우에는 shape 변화가 2개의 (3 x 4) -> 1개의 (3 x 4 x 2)가 됩니다

In [105]:
c1 = np.ones((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [106]:
c2 = np.zeros((3,4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [107]:
np.dstack([c1,c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [108]:
np.dstack([c1,c2]).shape

(3, 4, 2)

In [109]:
#stack 명령은 dstack의 기능을 확장한 것으로 
#dstack처럼 마지막 차원으로 연결하는 것이 아니라 
#사용자가 지정한 차원(축으로) 배열을 연결합니다. 
#axis 인수(디폴트 0)를 사용하여 연결후의 회전 방향을 정합니다. 
#디폴트 인수값은 0이고 가장 앞쪽에 차원이 생성됩니다. 
#즉, 배열 두 개가 겹치게 되므로 연결하고자 하는 배열들의 크기가 모두 같아야 합니

In [110]:
#다음 예에서는 axis=0 이므로 가장 바깥에 값이 2인 차원이 추가됩니다. 즉, shape 변화는 
#2개의 (3 x 4) -> 1개의 (2 x 3 x 4) 입니다
c = np.stack([c1,c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [111]:
c = np.stack([c1,c2],axis = 0) #합을 차원끼리 하겠다..?깊이,,,
c #두개를 합치므로 맨 앞이 2

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [112]:
c.shape

(2, 3, 4)

In [113]:
c = np.stack([c1,c2],axis = 1) #합을 행끼리 하겠다
c #두개를 합치므로 중간이 2

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [114]:
c.shape

(3, 2, 4)

In [115]:
c = np.stack([c1,c2],axis = 2) #합을 열끼리 하겠다
c #두개를 합치므로 마지막이 2

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [116]:
c.shape #맨 앞은 층수

(3, 4, 2)

In [117]:
#r_메서드
#hstack 명령과 비슷하게 배열을 좌우로 연결합니다. 
#다만 메서드임에도 불구하고 소괄호(parenthesis, ())를 사용하지 않고 
#인덱싱과 같이 대괄호(bracket, [])를 사용합니다. 
#이런 특수 메서드를 인덱서(indexer)라고 합니다
np.r_[np.array([1,2,3]),np.array([4,5,6])]
#표현방식에 hsteak과 차이가 없다

array([1, 2, 3, 4, 5, 6])

In [118]:
#c_메서드
#배열의 차원을 증가시킨 후 좌우로 연결합니다. 
#만약 1차원 배열을 연결하면 2차원 배열이 됩니다
#컬럼 단위로 합침
np.c_[np.array([1,2,3]),np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [119]:
#tile 명령
#동일한 배열을 반복하여 연결합니다
a = np.array([[0,1,2],[3,4,5]])
np.tile(a,2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [120]:
np.tile(a,(3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])