In [1]:
#정렬
#numpy.sort()를 사용하여 배열 안의 원소를 크기에 따라 정렬하여 새로운 배열을 만들 수도 있습니다.
#2차원 이상인 경우에는 행이나 열을 각각 따로따로 정렬하는데 
#axis 인수를 사용하여 행을 정렬할 것인지 열을 정렬한 것인지 결정합니다. 
#axis=0이면 각각의 행을 따로따로 정렬하고 axis=1이면 각각의 열을 따로따로 정렬합니다. 
#디폴트 값은 -1 즉 가장 안쪽(나중)의 차원입니다.

In [2]:
import numpy as np
a = np.array([[4,3,5,7],
              [1,12,11,9],
              [2,15,1,14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [3]:
np.sort(a) #axis = -1 또는 axis =1과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [4]:
np.sort(a,axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [5]:
#ndarray.sort() 메서드
#해당 객체의 자료 자체가 변화하는 자체변화(in-place) 메서드이므로 사용할 때 주의를 기울여야 합니다

In [6]:
a = np.array([[4,3,5,7],
              [1,12,11,9],
              [2,15,1,14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [7]:
a.sort(axis = 1) #주의!!
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [8]:
#만약 자료를 정렬하는 것이 아니라 순서만 알고 싶다면 argsort 명령을 사용합니다

In [9]:
a = np.array([42,38,12,25]) #오름차순 순서대로 인덱스를 가져옴
#a[0] = 42
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [10]:
a[j]

array([12, 25, 38, 42])

In [11]:
np.sort(a)

array([12, 25, 38, 42])

In [12]:
#고급 인덱싱 - 인덱스 배열을 사용한 인덱싱
#인덱싱을 할 때 인덱스 위치를 나타내는 배열을 활용하여 인덱싱이 가능하다. 
#아래의 예제 코드를 살펴보면 a[0, 0], a[1, 1], a[2, 0]을 인덱스로 하는 값을 각각 인덱싱하는 것을 볼 수 있다

In [13]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
print(a[[0,1,2],[0,1,0]]) #행/열 [0,0][1,1][2,0]
#a[0,0] a[1,1] a[2,0]을 인덱스로 하는 1차원 배열(shape = 3,))을 출력한다

[1 4 5]


In [15]:
#슬라이싱 범위도 결국 인덱스 배열이라고 생각하면 됩니다.
#아래의 예제에서는 행에 대해서는 슬라이싱 전체 범위를 표현하고 있는데 
#이는 [0, 1, 2]라는 범위를 나타내는 인덱스 배열과 동일한 결과를 가져옵니다.

In [16]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
print(a[:,[0,1,0]])

[[1 2 1]
 [3 4 3]
 [5 6 5]]


In [18]:
#연습문제
#다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 
#영어 성적을 기준으로 각 열(column)을 재정렬해보세요.

scores = np.array([[1,2,3,4],
                   [46,99,100,71],
                   [81,59,99,100]])

In [19]:
a = np.array([46,99,100,71]) #오름차순 순서대로 인덱스를 가져옴
j = np.argsort(a)
j

array([0, 3, 1, 2], dtype=int64)

In [20]:
print(scores[:,j])

[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  99]]


In [21]:
rank = np.argsort(scores[1,:])
rank

array([0, 3, 1, 2], dtype=int64)

In [22]:
print(scores[:,rank])

[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  99]]


In [23]:
#기술 통계

In [24]:
#넘파이는 다음과 같은 데이터 집합에 대해 간단한 통계를 계산하는 함수를 제공합니다. 
#이러한 값들을 통틀어 기술 통계(descriptive statistics)라고 합니다.

In [25]:
# 데이터의 개수(count)
#● 평균(mean, average)
#● 분산(variance)
#● 표준 편차(standard deviation)
#● 최대값(maximum)
#● 최소값(minimum)
#● 중앙값(median)
#● 사분위수(quartile)

In [26]:
#예를 들어 다음과 같은 데이터 𝑥가 있다고 해봅시다.
#𝑥 를 이루는 숫자 하나하나를 수학 기호로는 𝑥1,𝑥2,⋯,𝑥𝑁처럼 표시합니다. 
#위 예에서 𝑥1=18, 𝑥2=5 입니다.
#넘파이에서는 이러한 데이터를 1차원 배열로 구현합니다

In [27]:
#데이터의 개수
#len 함수
x = np.array([18,5,10,23,19,-8,10,0,0,5,2,15,8,
              2,5,4,15,-1,4,-7,-24,7,9,-6,23,-13])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [28]:
len(x)

26

In [29]:
#표본 평균
np.mean(x)

4.8076923076923075

In [30]:
#표본 분산
#데이터와 표본 평균간의 거리의 제곱의 평균
#표본 분산이 작으면 데이터가 모여있는 것이고 크면 흩어져 있는 것
np.var(x)

115.23224852071006

In [31]:
#표본 표준편차 #표본 분산의 양의 제곱근 값
np.std(x)

10.734628476137871

In [33]:
#최대값 최소값
np.min(x)

-24

In [33]:
#최대값 최소값
np.min(x)

-24

In [34]:
#중앙값
#데이터를 크기대로 정렬하였을 때 가장 가운데에 있는 수를 말합니다. 
#만약 데이터의 수가 짝수이면 가장 가운데에 있는 두 수의 평균을 사용합니다
np.median(x)

5.0

In [35]:
#사분위수
#데이터를 가장 작은 수부터 가장 큰 수까지 
#크기가 커지는 순서대로 정렬하였을 때 
#1/4, 2/4, 3/4 위치에 있는 수를 말합니다. 
#각각 1사분위수, 2사분위수, 3사분위수라고 합니다. 
#1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%를 말합니다. 
#따라서 2사분위수는 중앙값과 같습니다

In [36]:
#때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 한다. 
#1사분위수는 25% 백분위수와 같다

In [37]:
np.min(x) #최소값

-24

In [38]:
np.median(x) #중앙값

5.0

In [39]:
np.percentile(x,0) #최소값

-24.0

In [40]:
np.percentile(x,25) #1사분위 수

0.0

In [41]:
np.percentile(x,50) #2사분위 수

5.0

In [42]:
np.percentile(x,75)#3사분위 수

10.0

In [43]:
np.percentile(x,100) #최대값

23.0

In [44]:
#난수 발생과 카운팅
#파이썬을 이용하여 데이터를 무작위로 섞거나 임의의 수 
#즉, 난수(random number)를 발생시키는 방법
#NumPy의 random 서브패키지에서 제공합니다.
#표준 라이브러리인 random과 다릅니다.

In [45]:
#시드 설정하기

In [46]:
#어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성
#기준이 되는 시작 숫자를 시드(seed)라고 합니다.  
#생성된 난수는 다음 번 난수 생성을 위한 시드값이 됩니다. 
#따라서 시드값은 한 번만 정해주면 됩니다. 
#시드는 보통 현재 시각을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있습니다. 
#특정한 시드 값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측할 수 있습니다. 
#이 책에서는 코드의 결과를 재현하기 위해 항상 시드를 설정하고 데이터를 다뤄보겠습니다

In [47]:
np.random.seed(0)

In [48]:
#이렇게 시드를 설정한 후 넘파이 random 서브패키지에 있는 rand 함수로 5개의 난수를 생성
#rand 함수는 0과 1사이의 난수를 발생시키는 함수로 인수로 받은 숫자 횟수만큼 난수를 발생시킵니다
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [49]:
#몇 번 더 난수를 생성해보세요. 사람이 예측할 수 없는 무작위 숫자가 나오는 것을 볼 수 있습니다.
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [50]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [51]:
#이제 시드를 0으로 재설정하고 다시 난수를 발생시켜 보세요.
np.random.seed(0)

In [52]:
#그럼 아까와 같은 숫자가 나오는 것을 확인할 수 있습니다
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [53]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [54]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [55]:
#데이터의 순서 바꾸기

In [56]:
#데이터의 순서를 바꾸려면 shuffle 함수를 사용합니다. 
#shuffle 함수도 자체 변환(in-place) 함수로 한 번 사용하면 변수의 값이 바뀝니다.

In [57]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.random.shuffle(x)
x

array([3, 6, 4, 5, 2, 9, 7, 8, 1, 0])

In [59]:
#데이터 샘플링
#이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것
#표본선택 혹은 샘플링(sampling)이라고 합니다. 
#샘플링에는 choice 함수를 사용합니다. 
#choice 함수는 다음과 같은 인수를 가질 수 있습니다.
#numpy.random.choice(a, size=None, replace=True, p=None)
#● a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
#● size : 정수. 샘플 숫자.
#● replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능.
#● p : 배열. 각 데이터가 선택될 수 있는 확률

In [60]:
#np.random.choice()의 첫 인수를 정수 5로 전달하여 np.arange(5)의 결과를 만들었습니다

In [61]:
np.random.choice(5,5,replace = False) #shuffle명령과 같다

array([1, 4, 0, 3, 2])

In [62]:
np.random.choice(5,3,replace = False) #3개만 선텍

array([2, 1, 3])

In [63]:
np.random.choice(5,10) #반복해서 10개 선택

array([0, 4, 1, 4, 1, 2, 2, 0, 1, 1])

In [64]:
np.random.choice(5,10,p = [0.1,0, 0.3, 0.6, 0])
#선택확률을 다르게 해서 10개 선택

array([0, 3, 3, 2, 2, 3, 3, 2, 0, 3])

In [65]:
#난수 생성

In [66]:
#● rand: 0부터 1사이의 균일 분포
#● randn: 표준 정규 분포
#● randint: 균일 분포의 정수 난수

In [67]:
#rand 함수는 0부터 1사이에서 균일한 확률 분포로 실수 난수를 생성합니다. 
#숫자 인수는 생성할 난수의 크기입니다. 
#여러개의 인수를 넣으면 해당 shape를 가진 행렬을 생성합니다
np.random.rand(10)

array([0.95894927, 0.65279032, 0.63505887, 0.99529957, 0.58185033,
       0.41436859, 0.4746975 , 0.6235101 , 0.33800761, 0.67475232])

In [68]:
np.random.rand(3,5)

array([[0.31720174, 0.77834548, 0.94957105, 0.66252687, 0.01357164],
       [0.6228461 , 0.67365963, 0.971945  , 0.87819347, 0.50962438],
       [0.05571469, 0.45115921, 0.01998767, 0.44171092, 0.97958673]])

In [69]:
#randn 함수는 기댓값(mean)이 0이고 표준편차가 1인 표준 정규 분포(standard normal distribution)를 따르는 난수를 생성합니다. 
#인수 사용법은 rand 명령과 같습니다
np.random.randn(10)

array([-0.30237513, -2.2244036 ,  0.72400636,  0.35900276,  1.07612104,
        0.19214083,  0.85292596,  0.01835718,  0.42830357,  0.99627783])

In [70]:
np.random.randn(3,5)

array([[-0.49114966,  0.71267817,  1.11334035, -2.15367459, -0.41611148],
       [-1.07089699,  0.22113881, -1.12305712, -1.05075796,  1.01207905],
       [ 1.54371643, -0.40211489,  0.8647491 , -0.22686923,  0.81116027]])

In [71]:
#randint 함수는 다음과 같은 인수를 가집니다.
#numpy.random.randint(low, high=None, size=None)
#만약 high를 입력하지 않으면 0과 low사이의 숫자를, 
#high를 입력하면 low와 high 사이의 숫자를 출력합니다. 

In [72]:
np.random.randint(10,size = 10)

array([0, 4, 3, 6, 9, 8, 0, 8, 5, 9])

In [73]:
np.random.randint(10,20,size = 10)

array([10, 19, 16, 15, 13, 11, 18, 10, 14, 19])

In [74]:
np.random.randint(10,20,size = (3,5))
#size는 난수의 개수입니다.
#high의 범위는 포함하지 않습니다

array([[16, 15, 17, 18, 18],
       [19, 12, 18, 16, 16],
       [19, 11, 16, 18, 18]])

In [79]:
np.random.seed(0)
r = np.random.randint(0,2,size = 100)
np.mean(r)

3.42

In [79]:
np.random.seed(0)
r = np.random.randint(0,2,size = 100)
np.mean(r)

3.42

In [80]:
#정수 데이터 카운팅
#난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석할 수 있습니다.
#unique() 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력합니다. 
#return_counts 인수를 True 로 설정하면 각 값의 데이터 개수도 출력합니다

In [82]:
np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [83]:
a = np.array(['a','b','b','c','a'])
index,count = np.unique(a, return_counts = True)

In [84]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [85]:
count

array([2, 2, 1], dtype=int64)

In [86]:
#그러나 unique()는 데이터에 존재하는 값에 대해서만 개수를 세므로 
#데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는 경우에는 
#정보를 주지 않습니다. 
#예를 들어 주사위를 10번 던졌는데 6이 한 번도 나오지 않으면
#이 값을 0으로 세어주지 않습니다.
#따라서 데이터가 주사위를 던졌을 때 나오는 수처럼 특정 범위안의 수인 경우에는 
#bincount 함수에 minlength 인수를 설정하여 쓰는 것이 더 편리하다. 
#bincount 함수는 0 부터 minlength - 1 까지의 숫자에 대해 각각 카운트를 합니다. 
#데이터가 없을 경우에는 카운트 값이 0이 됩니다

In [87]:
np.bincount([1,1,2,2,2,3],minlength = 6)

array([0, 2, 3, 1, 0, 0], dtype=int64)