In [1]:
import numpy as np

In [2]:
np.random.seed(0)
a = np.random.randint(1,7,100)
np.mean(a)

3.42

In [3]:
#array([[1, 2, 3], [4, 5, 6]]) 과 array([[7, 8, 9], [10, 11, 12]]를 만들고 이 두 넘파이 배열을 활용하여 아래의 계산 결과를 구해보세요
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])
x+y

array([[ 8, 10, 12],
       [14, 16, 18]])

In [4]:
d = np.array([_ for _ in range(1,10)])
aws = [3 * i for i in d]
aws

[3, 6, 9, 12, 15, 18, 21, 24, 27]

In [5]:
d = np.array([_ for _ in range(1,10)])
3 * d

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [8]:
b = np.arange(50)
b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [9]:
#빈 문자열을 갖는 shape이 (3, 3, 3) ndarray를 만들어봅시다. 단 dtype은 ‘<U10’으로 합니다
c = np.arange(9)
np.zeros((3,3,3),dtype="<U10")

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

# np.full()

In [10]:
#하나의 특정 값으로 배열의 값을 채우고 싶을 때
#첫번째 인자는 shape을 두번째 인자에는 요소로 채울 값을 전달하면 됩니다. 
#타입 명기를 원하면 dtype 키워드 인수를 작성하면 됩니다

In [11]:
a = np.zeros((3,3,3), dtype = 'U8')
a[:] = 'playdata'
a

array([[['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']]], dtype='<U8')

In [12]:
a7 = np.full((3, 3, 3), 'playdata')
a7

array([[['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']],

       [['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata'],
        ['playdata', 'playdata', 'playdata']]], dtype='<U8')

In [13]:
a = np.arange(2,41,2).reshape(2,2,5)
a


array([[[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20]],

       [[22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40]]])

## 단위행렬만들기

In [14]:
#단위행렬만들기
#대각선 1값 나머지 0 /정사각형
# np.eye(n)

In [15]:
np.eye(4, dtype='i')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

## astype()메서드 : 타입 변경 dtype은 값을 필수로 입력

In [16]:
np.random.seed(0) # 내꺼임
a = np.random.randint(0,2,9)
a.astype('?').reshape(3,3)

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [17]:
np.random.seed(0)    # 진명님 풀이
a9 = np.random.randint(0, 2, 9).astype('?').reshape(3, 3)
a9

array([[False,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [18]:
np.random.seed(0)
x = (np.random.rand(10)*10).astype('i')
x

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3], dtype=int32)

In [19]:
np.random.seed(0)
a10 = (np.random.rand(10)*10).astype('i')
a10

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3], dtype=int32)

In [20]:
x = np.ones((10,10))
x[1:9, 1:9] = 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
x = np.ones((10,10))
x[0:10,0:10:9] = 0
x[0:10:9,0:10] = 0
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
x = np.ones((8,8))
x[1:9:2,0:9:2] = 0 #홀수줄
x[0:9:2,1:9:2] = 0 #짝수줄
x

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [23]:
f = np.array([[1,0],[0,1]])
np.tile(f,(4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [24]:
f = np.eye(2)
np.tile(f,(4,4))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# boolean indexing

In [25]:
#같은 shape과 len의 boolean type의 값을 갖는 ndarray로 인덱싱
#해당 위치에 대해 True면 값을 취하고 False면 가져오지 않습니다.
#예제) 1부터 4까지의 정수에서 짝수에 대해서만 인덱싱을 boolean indexing

In [26]:
a = np.arange(1,5)
print(a)

[1 2 3 4]


In [27]:
even = np.array([True if i%2 == 0 else False for i in range(1,5)])
print(even)

[False  True False  True]


In [28]:
#True와 False만 갖는 dtype('bool')의 ndarray를 인덱스로 사용
#인덱스로 쓰려면 shape과 len이 같아야 함
#각 인덱스 별로 비교를 하는데 인덱스로 쓰인 ndarray의 값이 True인 곳의 값만 반환

In [29]:
a[even]

array([2, 4])

In [30]:
#연습문제

In [31]:
s = np.array([i*True if 4>i or 7<=i else -i for i in range(11)]) #내꺼
print(s)              

[ 0  1  2  3 -4 -5 -6  7  8  9 10]


In [32]:
a15 = np.arange(11)    #진명님꺼
minus = np.array([-1*True if 3 < i < 7 else True for i in range(11)])
a15_minus = a15*minus
a15_minus

array([ 0,  1,  2,  3, -4, -5, -6,  7,  8,  9, 10])

In [33]:
#연습문제

In [34]:
a = np.arange(3,101,3)
a.sum()

1683

In [35]:
a = np.arange(1,101)
sum = np.array([True if i%3 == 0 else False for i in range(1,101)])
a2 = a[sum]
np.sum(a2) #개수가 똑같음
#boolean index did not match indexed array along dimension 0; dimension is 33 but corresponding boolean dimension is 100

1683

In [36]:
#연습문제

In [37]:
c = np.linspace(0.1,0.9,9)
c

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [38]:
#연습문제

In [39]:
while True: #진명님
    try:
        a = int(input())
        if a<0 :
            print("자연수만 입력해주세요.")
            continue
        else:
            for i in range(a):
                num = []
                d = np.random.choice(range(1,45),6,replace = False)
                num.extend(d)
                num.sort()
                print(num)   
        break
    except ValueError:
        print("자연수만 입력해주세요.")
        continue

 4


[7, 31, 33, 34, 36, 37]
[3, 14, 24, 29, 31, 42]
[13, 17, 36, 39, 41, 44]
[2, 11, 18, 22, 23, 30]


In [40]:
while True:
    try:
        number = int(input())
        if number>0:
            for _ in range(number):
                result = np.random.choice(range(1, 46), size=6, replace=False)
                result.sort()
                print(result)
            break
        else:
            print("자연수만 입력해주세요.")
    except ValueError:
        print("자연수만 입력해주세요.")
        continue

 5


[10 15 18 33 34 42]
[ 7 17 20 29 31 34]
[ 5 20 27 35 44 45]
[ 2  3  7 13 22 42]
[ 6 12 15 20 26 45]


In [41]:
while True: #기영님,,깰꼼,,
    n = input("자연수를 입력해주세요.")
    try:
        for i in range(int(n)):
            k = np.array([np.random.choice(np.arange(1, 46), replace=False) for _ in range(6)])
            print(np.sort(k))
        break;
    except ValueError:
        print("자연수를 입력해주세요.")

자연수를 입력해주세요. 5


[ 2 14 20 23 26 34]
[14 15 20 26 27 33]
[ 1 14 23 25 34 45]
[ 4  4  9 31 39 45]
[ 1  4  6 10 17 26]


In [42]:
resp_time = np. array([158, 85, 205, 24, 42, 175, 188, 149, 153, 171, 137, 55, 108,
 199, 177, 209, 218, 76, 103, 189, 110, 192, 136, 119, 4, 102,
 177, 212, 110, 37, 163, 32, 77, 22, 125, 184, 46, 139, 72,
 168, 133, 209, 148, 47, 102, 65, 160, 56, 11, 96, 169, 118,
 55, 135, 217, 49, 100, 85, 179, 15, 139, 199, 124, 142, 15,
 49, 168, 171, 168, 177, 147, 23, 199, 26, 51, 42, 90, 128,
 186, 169, 129, 70, 198, 111, 81, 150, 17, 177, 201, 10, 75,
 199, 55, 151, 183, 152, 119, 193, 110, 204])
result = np.array([True if i>200 else False for i in resp_time])
len(resp_time[result])

8

In [43]:
resp_time = np. array([158, 85, 205, 24, 42, 175, 188, 149, 153, 171, 137, 55, 108,
 199, 177, 209, 218, 76, 103, 189, 110, 192, 136, 119, 4, 102,
 177, 212, 110, 37, 163, 32, 77, 22, 125, 184, 46, 139, 72,
 168, 133, 209, 148, 47, 102, 65, 160, 56, 11, 96, 169, 118,
 55, 135, 217, 49, 100, 85, 179, 15, 139, 199, 124, 142, 15,
 49, 168, 171, 168, 177, 147, 23, 199, 26, 51, 42, 90, 128,
 186, 169, 129, 70, 198, 111, 81, 150, 17, 177, 201, 10, 75,
 199, 55, 151, 183, 152, 119, 193, 110, 204])
np.percentile(resp_time,25)

71.5

In [44]:
np.percentile(resp_time,50)

131.0

In [45]:
np.percentile(resp_time,75)

175.5

In [46]:
np.percentile(resp_time,100)

218.0

In [47]:
for i, v in enumerate(range(25, 76, 25)): #선생님
    print(f"{i + 1}분위({v}값%) 값: {np.percentile(resp_time, v)}ms")

1분위(25값%) 값: 71.5ms
2분위(50값%) 값: 131.0ms
3분위(75값%) 값: 175.5ms


In [48]:
np.quantile(resp_time, 0.75) #기영님

175.5

In [49]:
import numpy as np

p = ["Pororo", "Loopy", "Crong"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
 1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
 2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
 2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
 2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
 1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
 2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
 0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
 0, 1])

counts = [0, 0, 0]

for i in result:
    counts[i] += 1

winner_index = np.argmax(counts)
print(f"{p[winner_index]}가 {counts[winner_index]}표로 학생회장으로 선출되었습니다.")

Pororo가 81표로 학생회장으로 선출되었습니다.


In [50]:
import numpy as np

p = ["Pororo", "Rupee", "Crong"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
 1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
 2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
 2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
 2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
 1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
 2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
 0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
 0, 1])
counts = np.bincount(result)
vote_count = dict(zip(p, counts))
print(vote_count)

{'Pororo': 81, 'Rupee': 53, 'Crong': 66}


In [51]:
import numpy as np

p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
 1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
 2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
 2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
 2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
 1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
 2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
 0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
 0, 1])
counts = np.bincount(result)
print(f"{p[counts.argmax()]} 가 {counts.max()}표로 학생회장으로 선출되었습니다.")

뽀로로 가 81표로 학생회장으로 선출되었습니다.
